//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: intent_guard
// ----------------------------------------------------------------------------
pub mod intent_guard {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for intent_guard
    pub fn program_id() -> Pubkey {
        pubkey!("4etWfDJNHhjYdv7fuGe236GDPguwUXVk9WhbEpQsPix7")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: CommitIntent
    // ....................................................................

    /// Main instruction struct for CommitIntent
    pub struct CommitIntentInstruction {
        pub accounts: CommitIntentInstructionAccountMetas,
        pub data: CommitIntentInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for CommitIntent instruction
    #[derive(Debug, Clone, Default)]
    pub struct CommitIntentInstructionAccountMetas {
        pub intent_commit: AccountMeta,

        pub config: AccountMeta,

        pub user: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for CommitIntent instruction
    #[derive(Debug, Clone)]
    pub struct CommitIntentInstructionAccounts {
        pub intent_commit: Pubkey,

        pub config: Pubkey,

        pub user: Pubkey,
    }

    impl CommitIntentInstructionAccounts {
        pub fn new(intent_commit: Pubkey, config: Pubkey, user: Pubkey) -> Self {
            Self {
                intent_commit,

                config,

                user,
            }
        }
    }

    /// Instruction data for CommitIntent
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct CommitIntentInstructionData {
        pub app_id: Pubkey,

        pub intent_hash: [u8; 32],

        pub ttl: i64,
    }

    impl CommitIntentInstructionData {
        pub fn new(app_id: Pubkey, intent_hash: [u8; 32], ttl: i64) -> Self {
            Self {
                app_id,

                intent_hash,

                ttl,
            }
        }
    }

    /// Implementation for CommitIntentInstruction
    impl CommitIntentInstruction {
        fn discriminator() -> [u8; 8] {
            [175u8, 152u8, 13u8, 10u8, 40u8, 234u8, 201u8, 8u8]
        }

        pub fn data(data: CommitIntentInstructionData) -> Self {
            Self {
                accounts: CommitIntentInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: CommitIntentInstructionAccounts) -> Self {
            self.accounts.intent_commit = AccountMeta::new(accounts.intent_commit, false);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.user = AccountMeta::new(accounts.user, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.intent_commit.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.user.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Initialize
    // ....................................................................

    /// Main instruction struct for Initialize
    pub struct InitializeInstruction {
        pub accounts: InitializeInstructionAccountMetas,
        pub data: InitializeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Initialize instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeInstructionAccountMetas {
        pub config: AccountMeta,

        pub admin: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for Initialize instruction
    #[derive(Debug, Clone)]
    pub struct InitializeInstructionAccounts {
        pub config: Pubkey,

        pub admin: Pubkey,
    }

    impl InitializeInstructionAccounts {
        pub fn new(config: Pubkey, admin: Pubkey) -> Self {
            Self { config, admin }
        }
    }

    /// Instruction data for Initialize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeInstructionData {}

    impl InitializeInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for InitializeInstruction
    impl InitializeInstruction {
        fn discriminator() -> [u8; 8] {
            [175u8, 175u8, 109u8, 31u8, 13u8, 152u8, 155u8, 237u8]
        }

        pub fn data(data: InitializeInstructionData) -> Self {
            Self {
                accounts: InitializeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: MigrateConfig
    // ....................................................................

    /// Main instruction struct for MigrateConfig
    pub struct MigrateConfigInstruction {
        pub accounts: MigrateConfigInstructionAccountMetas,
        pub data: MigrateConfigInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for MigrateConfig instruction
    #[derive(Debug, Clone, Default)]
    pub struct MigrateConfigInstructionAccountMetas {
        pub config: AccountMeta,

        pub admin: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for MigrateConfig instruction
    #[derive(Debug, Clone)]
    pub struct MigrateConfigInstructionAccounts {
        pub config: Pubkey,

        pub admin: Pubkey,
    }

    impl MigrateConfigInstructionAccounts {
        pub fn new(config: Pubkey, admin: Pubkey) -> Self {
            Self { config, admin }
        }
    }

    /// Instruction data for MigrateConfig
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct MigrateConfigInstructionData {}

    impl MigrateConfigInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for MigrateConfigInstruction
    impl MigrateConfigInstruction {
        fn discriminator() -> [u8; 8] {
            [92u8, 131u8, 58u8, 105u8, 210u8, 154u8, 224u8, 193u8]
        }

        pub fn data(data: MigrateConfigInstructionData) -> Self {
            Self {
                accounts: MigrateConfigInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: MigrateConfigInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: PauseProtocol
    // ....................................................................

    /// Main instruction struct for PauseProtocol
    pub struct PauseProtocolInstruction {
        pub accounts: PauseProtocolInstructionAccountMetas,
        pub data: PauseProtocolInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for PauseProtocol instruction
    #[derive(Debug, Clone, Default)]
    pub struct PauseProtocolInstructionAccountMetas {
        pub config: AccountMeta,

        pub admin: AccountMeta,
    }

    /// Account pubkeys for PauseProtocol instruction
    #[derive(Debug, Clone)]
    pub struct PauseProtocolInstructionAccounts {
        pub config: Pubkey,

        pub admin: Pubkey,
    }

    impl PauseProtocolInstructionAccounts {
        pub fn new(config: Pubkey, admin: Pubkey) -> Self {
            Self { config, admin }
        }
    }

    /// Instruction data for PauseProtocol
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct PauseProtocolInstructionData {}

    impl PauseProtocolInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for PauseProtocolInstruction
    impl PauseProtocolInstruction {
        fn discriminator() -> [u8; 8] {
            [144u8, 95u8, 0u8, 107u8, 119u8, 39u8, 248u8, 141u8]
        }

        pub fn data(data: PauseProtocolInstructionData) -> Self {
            Self {
                accounts: PauseProtocolInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: PauseProtocolInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.admin.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RevokeIntent
    // ....................................................................

    /// Main instruction struct for RevokeIntent
    pub struct RevokeIntentInstruction {
        pub accounts: RevokeIntentInstructionAccountMetas,
        pub data: RevokeIntentInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RevokeIntent instruction
    #[derive(Debug, Clone, Default)]
    pub struct RevokeIntentInstructionAccountMetas {
        pub intent_commit: AccountMeta,

        pub user: AccountMeta,
    }

    /// Account pubkeys for RevokeIntent instruction
    #[derive(Debug, Clone)]
    pub struct RevokeIntentInstructionAccounts {
        pub intent_commit: Pubkey,

        pub user: Pubkey,
    }

    impl RevokeIntentInstructionAccounts {
        pub fn new(intent_commit: Pubkey, user: Pubkey) -> Self {
            Self {
                intent_commit,

                user,
            }
        }
    }

    /// Instruction data for RevokeIntent
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RevokeIntentInstructionData {
        pub app_id: Pubkey,
    }

    impl RevokeIntentInstructionData {
        pub fn new(app_id: Pubkey) -> Self {
            Self { app_id }
        }
    }

    /// Implementation for RevokeIntentInstruction
    impl RevokeIntentInstruction {
        fn discriminator() -> [u8; 8] {
            [42u8, 248u8, 79u8, 132u8, 107u8, 96u8, 193u8, 153u8]
        }

        pub fn data(data: RevokeIntentInstructionData) -> Self {
            Self {
                accounts: RevokeIntentInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RevokeIntentInstructionAccounts) -> Self {
            self.accounts.intent_commit = AccountMeta::new(accounts.intent_commit, false);

            self.accounts.user = AccountMeta::new(accounts.user, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.intent_commit.clone());

            metas.push(self.accounts.user.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: TransferAdmin
    // ....................................................................

    /// Main instruction struct for TransferAdmin
    pub struct TransferAdminInstruction {
        pub accounts: TransferAdminInstructionAccountMetas,
        pub data: TransferAdminInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for TransferAdmin instruction
    #[derive(Debug, Clone, Default)]
    pub struct TransferAdminInstructionAccountMetas {
        pub config: AccountMeta,

        pub admin: AccountMeta,
    }

    /// Account pubkeys for TransferAdmin instruction
    #[derive(Debug, Clone)]
    pub struct TransferAdminInstructionAccounts {
        pub config: Pubkey,

        pub admin: Pubkey,
    }

    impl TransferAdminInstructionAccounts {
        pub fn new(config: Pubkey, admin: Pubkey) -> Self {
            Self { config, admin }
        }
    }

    /// Instruction data for TransferAdmin
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct TransferAdminInstructionData {
        pub new_admin: Pubkey,
    }

    impl TransferAdminInstructionData {
        pub fn new(new_admin: Pubkey) -> Self {
            Self { new_admin }
        }
    }

    /// Implementation for TransferAdminInstruction
    impl TransferAdminInstruction {
        fn discriminator() -> [u8; 8] {
            [42u8, 242u8, 66u8, 106u8, 228u8, 10u8, 111u8, 156u8]
        }

        pub fn data(data: TransferAdminInstructionData) -> Self {
            Self {
                accounts: TransferAdminInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: TransferAdminInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.admin.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UnpauseProtocol
    // ....................................................................

    /// Main instruction struct for UnpauseProtocol
    pub struct UnpauseProtocolInstruction {
        pub accounts: UnpauseProtocolInstructionAccountMetas,
        pub data: UnpauseProtocolInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UnpauseProtocol instruction
    #[derive(Debug, Clone, Default)]
    pub struct UnpauseProtocolInstructionAccountMetas {
        pub config: AccountMeta,

        pub admin: AccountMeta,
    }

    /// Account pubkeys for UnpauseProtocol instruction
    #[derive(Debug, Clone)]
    pub struct UnpauseProtocolInstructionAccounts {
        pub config: Pubkey,

        pub admin: Pubkey,
    }

    impl UnpauseProtocolInstructionAccounts {
        pub fn new(config: Pubkey, admin: Pubkey) -> Self {
            Self { config, admin }
        }
    }

    /// Instruction data for UnpauseProtocol
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UnpauseProtocolInstructionData {}

    impl UnpauseProtocolInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for UnpauseProtocolInstruction
    impl UnpauseProtocolInstruction {
        fn discriminator() -> [u8; 8] {
            [183u8, 154u8, 5u8, 183u8, 105u8, 76u8, 87u8, 18u8]
        }

        pub fn data(data: UnpauseProtocolInstructionData) -> Self {
            Self {
                accounts: UnpauseProtocolInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UnpauseProtocolInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.admin.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateConfig
    // ....................................................................

    /// Main instruction struct for UpdateConfig
    pub struct UpdateConfigInstruction {
        pub accounts: UpdateConfigInstructionAccountMetas,
        pub data: UpdateConfigInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateConfig instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateConfigInstructionAccountMetas {
        pub config: AccountMeta,

        pub admin: AccountMeta,
    }

    /// Account pubkeys for UpdateConfig instruction
    #[derive(Debug, Clone)]
    pub struct UpdateConfigInstructionAccounts {
        pub config: Pubkey,

        pub admin: Pubkey,
    }

    impl UpdateConfigInstructionAccounts {
        pub fn new(config: Pubkey, admin: Pubkey) -> Self {
            Self { config, admin }
        }
    }

    /// Instruction data for UpdateConfig
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateConfigInstructionData {
        pub new_min_balance: u64,
    }

    impl UpdateConfigInstructionData {
        pub fn new(new_min_balance: u64) -> Self {
            Self { new_min_balance }
        }
    }

    /// Implementation for UpdateConfigInstruction
    impl UpdateConfigInstruction {
        fn discriminator() -> [u8; 8] {
            [29u8, 158u8, 252u8, 191u8, 10u8, 83u8, 219u8, 99u8]
        }

        pub fn data(data: UpdateConfigInstructionData) -> Self {
            Self {
                accounts: UpdateConfigInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateConfigInstructionAccounts) -> Self {
            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.admin.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: VerifyIntent
    // ....................................................................

    /// Main instruction struct for VerifyIntent
    pub struct VerifyIntentInstruction {
        pub accounts: VerifyIntentInstructionAccountMetas,
        pub data: VerifyIntentInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for VerifyIntent instruction
    #[derive(Debug, Clone, Default)]
    pub struct VerifyIntentInstructionAccountMetas {
        pub intent_commit: AccountMeta,

        pub config: AccountMeta,

        pub user: AccountMeta,
    }

    /// Account pubkeys for VerifyIntent instruction
    #[derive(Debug, Clone)]
    pub struct VerifyIntentInstructionAccounts {
        pub intent_commit: Pubkey,

        pub config: Pubkey,

        pub user: Pubkey,
    }

    impl VerifyIntentInstructionAccounts {
        pub fn new(intent_commit: Pubkey, config: Pubkey, user: Pubkey) -> Self {
            Self {
                intent_commit,

                config,

                user,
            }
        }
    }

    /// Instruction data for VerifyIntent
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct VerifyIntentInstructionData {
        pub intent_hash: [u8; 32],
    }

    impl VerifyIntentInstructionData {
        pub fn new(intent_hash: [u8; 32]) -> Self {
            Self { intent_hash }
        }
    }

    /// Implementation for VerifyIntentInstruction
    impl VerifyIntentInstruction {
        fn discriminator() -> [u8; 8] {
            [240u8, 198u8, 213u8, 223u8, 94u8, 7u8, 247u8, 247u8]
        }

        pub fn data(data: VerifyIntentInstructionData) -> Self {
            Self {
                accounts: VerifyIntentInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: VerifyIntentInstructionAccounts) -> Self {
            self.accounts.intent_commit = AccountMeta::new(accounts.intent_commit, false);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.user = AccountMeta::new(accounts.user, true);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.intent_commit.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.user.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: GuardConfig
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct GuardConfig {
    pub admin: Pubkey,

    pub is_paused: bool,

    pub total_commits: u64,

    pub total_verifies: u64,

    pub min_balance: u64,

    pub bump: u8,
}

impl GuardConfig {
    pub fn new(
        admin: Pubkey,

        is_paused: bool,

        total_commits: u64,

        total_verifies: u64,

        min_balance: u64,

        bump: u8,
    ) -> Self {
        Self {
            admin,

            is_paused,

            total_commits,

            total_verifies,

            min_balance,

            bump,
        }
    }
}

/// Custom struct: IntentCommit
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct IntentCommit {
    pub user: Pubkey,

    pub app_id: Pubkey,

    pub intent_hash: [u8; 32],

    pub committed_at: i64,

    pub expires_at: i64,

    pub bump: u8,
}

impl IntentCommit {
    pub fn new(
        user: Pubkey,

        app_id: Pubkey,

        intent_hash: [u8; 32],

        committed_at: i64,

        expires_at: i64,

        bump: u8,
    ) -> Self {
        Self {
            user,

            app_id,

            intent_hash,

            committed_at,

            expires_at,

            bump,
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
